# Generated by Django 3.2.9 on 2021-12-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ip_usuario', models.GenericIPAddressField()),
                ('primeiro_nome', models.CharField(max_length=80, verbose_name='primeiro_nome')),
                ('sobrenome', models.CharField(max_length=80, verbose_name='sobrenome')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='username')),
                ('telefone', models.CharField(max_length=15, unique=True, verbose_name='telefone')),
                ('CEP', models.IntegerField()),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=150)),
                ('fav_esport', models.CharField(max_length=80)),
                ('altura', models.FloatField()),
                ('idade', models.IntegerField()),
                ('peso', models.FloatField()),
                ('genero', models.SmallIntegerField()),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
                ('rua', models.CharField(max_length=80)),
                ('CEP', models.IntegerField()),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('alugada', models.BooleanField(max_length=3)),
                ('estrelas', models.IntegerField()),
                ('valor_hora', models.IntegerField()),
                ('horario_funcionamento', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
        ),
    ]
