# Generated by Django 3.2.9 on 2021-12-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
                ('rua', models.CharField(max_length=80)),
                ('CEP', models.IntegerField()),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('alugada', models.BooleanField(default=False)),
                ('telefone', models.CharField(default=None, max_length=15, unique=True, verbose_name='telefone')),
                ('estrelas', models.IntegerField(default=0)),
                ('valor_hora', models.IntegerField(default=0)),
                ('horario_abertura', models.IntegerField(default=0)),
                ('horario_fechamento', models.IntegerField(default=0)),
                ('descricao', models.TextField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('primeiro_nome', models.CharField(max_length=80, verbose_name='primeiro_nome')),
                ('sobrenome', models.CharField(max_length=80, verbose_name='sobrenome')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='username')),
                ('telefone', models.CharField(default=None, max_length=15, unique=True, verbose_name='telefone')),
                ('CEP', models.CharField(max_length=8, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=150)),
                ('esportes_praticados', models.CharField(blank=True, max_length=150, null=True)),
                ('fav_esport', models.CharField(max_length=80)),
                ('altura', models.IntegerField(default=0)),
                ('idade', models.IntegerField(default=0)),
                ('peso', models.FloatField(default=0)),
                ('genero', models.CharField(default=0, max_length=1)),
                ('imagem', models.ImageField(default=None, upload_to='')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
