# Generated by Django 3.2.9 on 2021-12-02 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_usuario_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quadra',
            name='CEP',
        ),
        migrations.RemoveField(
            model_name='quadra',
            name='alugada',
        ),
        migrations.RemoveField(
            model_name='quadra',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='quadra',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='quadra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='quadra',
            name='estrelas',
        ),
        migrations.RemoveField(
            model_name='quadra',
            name='horario_funcionamento',
        ),
        migrations.RemoveField(
            model_name='quadra',
            name='valor_hora',
        ),
    ]
