# Generated by Django 3.2.9 on 2021-12-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_room_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_quadra', models.IntegerField()),
                ('tipo', models.CharField(max_length=80)),
                ('rua', models.CharField(max_length=80)),
                ('CEP', models.IntegerField()),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('alugada', models.BooleanField(max_length=3)),
                ('estrelas', models.IntegerField()),
                ('valor_hora', models.IntegerField()),
                ('horario_funcionamento', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('ip_usuario', models.GenericIPAddressField()),
                ('primeiro_nome', models.CharField(max_length=80)),
                ('sobrenome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('username', models.CharField(max_length=15)),
                ('CEP', models.IntegerField()),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=150)),
                ('fav_esport', models.CharField(max_length=80)),
                ('altura', models.FloatField()),
                ('idade', models.IntegerField()),
                ('peso', models.FloatField()),
                ('genero', models.SmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='index',
        ),
    ]
