# Generated by Django 3.2.9 on 2021-12-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211201_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quadra',
            name='id_quadra',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
    ]
