# Generated by Django 3.2.9 on 2021-12-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_usuario_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quadra',
            name='horario_funcionamento',
        ),
        migrations.AddField(
            model_name='quadra',
            name='horario_abertura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quadra',
            name='horario_fechamento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quadra',
            name='telefone',
            field=models.CharField(default=None, max_length=15, unique=True, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='esportes_praticados',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='alugada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='descricao',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='estrelas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='valor_hora',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default=None, max_length=15, unique=True, verbose_name='telefone'),
        ),
    ]
